// Generated by gencpp from file publisher_subscriber/CalculateHexCodeRequest.msg
// DO NOT EDIT!


#ifndef PUBLISHER_SUBSCRIBER_MESSAGE_CALCULATEHEXCODEREQUEST_H
#define PUBLISHER_SUBSCRIBER_MESSAGE_CALCULATEHEXCODEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace publisher_subscriber
{
template <class ContainerAllocator>
struct CalculateHexCodeRequest_
{
  typedef CalculateHexCodeRequest_<ContainerAllocator> Type;

  CalculateHexCodeRequest_()
    : r(0)
    , g(0)
    , b(0)  {
    }
  CalculateHexCodeRequest_(const ContainerAllocator& _alloc)
    : r(0)
    , g(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef uint8_t _r_type;
  _r_type r;

   typedef uint8_t _g_type;
  _g_type g;

   typedef uint8_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::publisher_subscriber::CalculateHexCodeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::publisher_subscriber::CalculateHexCodeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CalculateHexCodeRequest_

typedef ::publisher_subscriber::CalculateHexCodeRequest_<std::allocator<void> > CalculateHexCodeRequest;

typedef boost::shared_ptr< ::publisher_subscriber::CalculateHexCodeRequest > CalculateHexCodeRequestPtr;
typedef boost::shared_ptr< ::publisher_subscriber::CalculateHexCodeRequest const> CalculateHexCodeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::publisher_subscriber::CalculateHexCodeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::publisher_subscriber::CalculateHexCodeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::publisher_subscriber::CalculateHexCodeRequest_<ContainerAllocator1> & lhs, const ::publisher_subscriber::CalculateHexCodeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.r == rhs.r &&
    lhs.g == rhs.g &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::publisher_subscriber::CalculateHexCodeRequest_<ContainerAllocator1> & lhs, const ::publisher_subscriber::CalculateHexCodeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace publisher_subscriber

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::publisher_subscriber::CalculateHexCodeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::publisher_subscriber::CalculateHexCodeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::publisher_subscriber::CalculateHexCodeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::publisher_subscriber::CalculateHexCodeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::publisher_subscriber::CalculateHexCodeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::publisher_subscriber::CalculateHexCodeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::publisher_subscriber::CalculateHexCodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "353891e354491c51aabe32df673fb446";
  }

  static const char* value(const ::publisher_subscriber::CalculateHexCodeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x353891e354491c51ULL;
  static const uint64_t static_value2 = 0xaabe32df673fb446ULL;
};

template<class ContainerAllocator>
struct DataType< ::publisher_subscriber::CalculateHexCodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "publisher_subscriber/CalculateHexCodeRequest";
  }

  static const char* value(const ::publisher_subscriber::CalculateHexCodeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::publisher_subscriber::CalculateHexCodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 r\n"
"uint8 g\n"
"uint8 b\n"
;
  }

  static const char* value(const ::publisher_subscriber::CalculateHexCodeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::publisher_subscriber::CalculateHexCodeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.r);
      stream.next(m.g);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CalculateHexCodeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::publisher_subscriber::CalculateHexCodeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::publisher_subscriber::CalculateHexCodeRequest_<ContainerAllocator>& v)
  {
    s << indent << "r: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.r);
    s << indent << "g: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.g);
    s << indent << "b: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PUBLISHER_SUBSCRIBER_MESSAGE_CALCULATEHEXCODEREQUEST_H
