// Generated by gencpp from file publisher_subscriber/CalculateHexCode.msg
// DO NOT EDIT!


#ifndef PUBLISHER_SUBSCRIBER_MESSAGE_CALCULATEHEXCODE_H
#define PUBLISHER_SUBSCRIBER_MESSAGE_CALCULATEHEXCODE_H

#include <ros/service_traits.h>


#include <publisher_subscriber/CalculateHexCodeRequest.h>
#include <publisher_subscriber/CalculateHexCodeResponse.h>


namespace publisher_subscriber
{

struct CalculateHexCode
{

typedef CalculateHexCodeRequest Request;
typedef CalculateHexCodeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CalculateHexCode
} // namespace publisher_subscriber


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::publisher_subscriber::CalculateHexCode > {
  static const char* value()
  {
    return "7638e56a2e7114ce46865d393cb9b4d9";
  }

  static const char* value(const ::publisher_subscriber::CalculateHexCode&) { return value(); }
};

template<>
struct DataType< ::publisher_subscriber::CalculateHexCode > {
  static const char* value()
  {
    return "publisher_subscriber/CalculateHexCode";
  }

  static const char* value(const ::publisher_subscriber::CalculateHexCode&) { return value(); }
};


// service_traits::MD5Sum< ::publisher_subscriber::CalculateHexCodeRequest> should match
// service_traits::MD5Sum< ::publisher_subscriber::CalculateHexCode >
template<>
struct MD5Sum< ::publisher_subscriber::CalculateHexCodeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::publisher_subscriber::CalculateHexCode >::value();
  }
  static const char* value(const ::publisher_subscriber::CalculateHexCodeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::publisher_subscriber::CalculateHexCodeRequest> should match
// service_traits::DataType< ::publisher_subscriber::CalculateHexCode >
template<>
struct DataType< ::publisher_subscriber::CalculateHexCodeRequest>
{
  static const char* value()
  {
    return DataType< ::publisher_subscriber::CalculateHexCode >::value();
  }
  static const char* value(const ::publisher_subscriber::CalculateHexCodeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::publisher_subscriber::CalculateHexCodeResponse> should match
// service_traits::MD5Sum< ::publisher_subscriber::CalculateHexCode >
template<>
struct MD5Sum< ::publisher_subscriber::CalculateHexCodeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::publisher_subscriber::CalculateHexCode >::value();
  }
  static const char* value(const ::publisher_subscriber::CalculateHexCodeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::publisher_subscriber::CalculateHexCodeResponse> should match
// service_traits::DataType< ::publisher_subscriber::CalculateHexCode >
template<>
struct DataType< ::publisher_subscriber::CalculateHexCodeResponse>
{
  static const char* value()
  {
    return DataType< ::publisher_subscriber::CalculateHexCode >::value();
  }
  static const char* value(const ::publisher_subscriber::CalculateHexCodeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PUBLISHER_SUBSCRIBER_MESSAGE_CALCULATEHEXCODE_H
