// Generated by gencpp from file publisher_subscriber/CalculateHexCodeResponse.msg
// DO NOT EDIT!


#ifndef PUBLISHER_SUBSCRIBER_MESSAGE_CALCULATEHEXCODERESPONSE_H
#define PUBLISHER_SUBSCRIBER_MESSAGE_CALCULATEHEXCODERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace publisher_subscriber
{
template <class ContainerAllocator>
struct CalculateHexCodeResponse_
{
  typedef CalculateHexCodeResponse_<ContainerAllocator> Type;

  CalculateHexCodeResponse_()
    : hexcode()  {
    }
  CalculateHexCodeResponse_(const ContainerAllocator& _alloc)
    : hexcode(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _hexcode_type;
  _hexcode_type hexcode;





  typedef boost::shared_ptr< ::publisher_subscriber::CalculateHexCodeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::publisher_subscriber::CalculateHexCodeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CalculateHexCodeResponse_

typedef ::publisher_subscriber::CalculateHexCodeResponse_<std::allocator<void> > CalculateHexCodeResponse;

typedef boost::shared_ptr< ::publisher_subscriber::CalculateHexCodeResponse > CalculateHexCodeResponsePtr;
typedef boost::shared_ptr< ::publisher_subscriber::CalculateHexCodeResponse const> CalculateHexCodeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::publisher_subscriber::CalculateHexCodeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::publisher_subscriber::CalculateHexCodeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::publisher_subscriber::CalculateHexCodeResponse_<ContainerAllocator1> & lhs, const ::publisher_subscriber::CalculateHexCodeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.hexcode == rhs.hexcode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::publisher_subscriber::CalculateHexCodeResponse_<ContainerAllocator1> & lhs, const ::publisher_subscriber::CalculateHexCodeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace publisher_subscriber

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::publisher_subscriber::CalculateHexCodeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::publisher_subscriber::CalculateHexCodeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::publisher_subscriber::CalculateHexCodeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::publisher_subscriber::CalculateHexCodeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::publisher_subscriber::CalculateHexCodeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::publisher_subscriber::CalculateHexCodeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::publisher_subscriber::CalculateHexCodeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac5cba6b02cfca058b49ce3559bc4354";
  }

  static const char* value(const ::publisher_subscriber::CalculateHexCodeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac5cba6b02cfca05ULL;
  static const uint64_t static_value2 = 0x8b49ce3559bc4354ULL;
};

template<class ContainerAllocator>
struct DataType< ::publisher_subscriber::CalculateHexCodeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "publisher_subscriber/CalculateHexCodeResponse";
  }

  static const char* value(const ::publisher_subscriber::CalculateHexCodeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::publisher_subscriber::CalculateHexCodeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string hexcode\n"
"\n"
;
  }

  static const char* value(const ::publisher_subscriber::CalculateHexCodeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::publisher_subscriber::CalculateHexCodeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hexcode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CalculateHexCodeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::publisher_subscriber::CalculateHexCodeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::publisher_subscriber::CalculateHexCodeResponse_<ContainerAllocator>& v)
  {
    s << indent << "hexcode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.hexcode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PUBLISHER_SUBSCRIBER_MESSAGE_CALCULATEHEXCODERESPONSE_H
