// Generated by gencpp from file publisher_subscriber/RGBColor.msg
// DO NOT EDIT!


#ifndef PUBLISHER_SUBSCRIBER_MESSAGE_RGBCOLOR_H
#define PUBLISHER_SUBSCRIBER_MESSAGE_RGBCOLOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace publisher_subscriber
{
template <class ContainerAllocator>
struct RGBColor_
{
  typedef RGBColor_<ContainerAllocator> Type;

  RGBColor_()
    : R(0)
    , G(0)
    , B(0)  {
    }
  RGBColor_(const ContainerAllocator& _alloc)
    : R(0)
    , G(0)
    , B(0)  {
  (void)_alloc;
    }



   typedef uint8_t _R_type;
  _R_type R;

   typedef uint8_t _G_type;
  _G_type G;

   typedef uint8_t _B_type;
  _B_type B;





  typedef boost::shared_ptr< ::publisher_subscriber::RGBColor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::publisher_subscriber::RGBColor_<ContainerAllocator> const> ConstPtr;

}; // struct RGBColor_

typedef ::publisher_subscriber::RGBColor_<std::allocator<void> > RGBColor;

typedef boost::shared_ptr< ::publisher_subscriber::RGBColor > RGBColorPtr;
typedef boost::shared_ptr< ::publisher_subscriber::RGBColor const> RGBColorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::publisher_subscriber::RGBColor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::publisher_subscriber::RGBColor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::publisher_subscriber::RGBColor_<ContainerAllocator1> & lhs, const ::publisher_subscriber::RGBColor_<ContainerAllocator2> & rhs)
{
  return lhs.R == rhs.R &&
    lhs.G == rhs.G &&
    lhs.B == rhs.B;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::publisher_subscriber::RGBColor_<ContainerAllocator1> & lhs, const ::publisher_subscriber::RGBColor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace publisher_subscriber

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::publisher_subscriber::RGBColor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::publisher_subscriber::RGBColor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::publisher_subscriber::RGBColor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::publisher_subscriber::RGBColor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::publisher_subscriber::RGBColor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::publisher_subscriber::RGBColor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::publisher_subscriber::RGBColor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25e8e0a5fcebfd5489b6ec59d3303e32";
  }

  static const char* value(const ::publisher_subscriber::RGBColor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25e8e0a5fcebfd54ULL;
  static const uint64_t static_value2 = 0x89b6ec59d3303e32ULL;
};

template<class ContainerAllocator>
struct DataType< ::publisher_subscriber::RGBColor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "publisher_subscriber/RGBColor";
  }

  static const char* value(const ::publisher_subscriber::RGBColor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::publisher_subscriber::RGBColor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 R\n"
"uint8 G\n"
"uint8 B\n"
;
  }

  static const char* value(const ::publisher_subscriber::RGBColor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::publisher_subscriber::RGBColor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.R);
      stream.next(m.G);
      stream.next(m.B);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RGBColor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::publisher_subscriber::RGBColor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::publisher_subscriber::RGBColor_<ContainerAllocator>& v)
  {
    s << indent << "R: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.R);
    s << indent << "G: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.G);
    s << indent << "B: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.B);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PUBLISHER_SUBSCRIBER_MESSAGE_RGBCOLOR_H
